### ISSUE TITLE
Add support for text and XPath selector

### ISSUE THREAD

**Issue by jecfish** [webdriverio/chrome-recorder#3]
DevTools Recorder support text and XPath selector from Chrome 108 onwards. I am wondering if there are similar selector in WebdriverIO?

Here is the example step's json.

```json
{
      "type": "click",
      "target": "main",
      "selectors": [
        [
          "aria/Proceed to checkout"
        ],
        [
          "[data-test=checkout]"
        ],
        [
          "xpath///*[@data-test=\"checkout\"]"
        ],
        [
          "text/Total: $0.00"
        ]
      ]
    }
```

<img width="500" alt="Screen Shot 2022-10-16 at 9 35 19 AM" src="https://user-images.githubusercontent.com/5917927/196023955-28e86ac8-fb1b-44ee-aa7a-006b7c4b9ec3.png">

**Comment by christian-bromann** [comment]
Oh awesome.

Right now WebdriverIO prefers aria selectors `aria/...` and [creates](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/utils/findStrategy.ts#L161-L189) an xPath from it based on the conditions described in the w3c protocol. We could change the current implementation to prefer the xPath if given by Chrome.

**Comment by christian-bromann** [comment]
Implemented that xPath is preferred selector after id and before aria label, given that aria labels are IMO less deterministic than xPaths. Thanks for filing the issue.
