### ISSUE TITLE
Update argument name for meow dependency

### ISSUE THREAD

**Issue by Seeker285** [webdriverio/chrome-recorder#6]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@wdio/chrome-recorder@0.5.2` for the project I'm working on.

The dependency "meow" is throwing the following error: 
```
Error: The option `alias` has been renamed to `shortFlag`. The following flags need to be updated: `--output`
```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@wdio/chrome-recorder/dist/cli/index.js b/node_modules/@wdio/chrome-recorder/dist/cli/index.js
index 08484db..5e2999b 100644
--- a/node_modules/@wdio/chrome-recorder/dist/cli/index.js
+++ b/node_modules/@wdio/chrome-recorder/dist/cli/index.js
@@ -27,7 +27,7 @@ const cli = meow(`
         },
         output: {
             type: 'string',
-            alias: 'o',
+            shortFlag: 'o',
         },
     },
 });
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by christian-bromann** [comment]
Thanks for reporting!

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!
